#!/bin/sh

RootSD=$(cd "$(dirname "$0")"; pwd)
RootSH=${RootSD}

export DEBIAN_FRONTEND=noninteractive

#curl -o "xxx" "http://jsoc2.stanford.edu/data/aia/images/2025/11/15/193/2025_11_15__11_01_28_835__SDO_AIA_AIA_193.jp2"
#rm   -rf xxx

k_repo_tag="v0.0.6"
export PATH=${RootSD}:${RootSH}:${PATH}

fn_install()
{
	echo "      >>>>> install ${1}"
	sudo apt-get install -y ${1} >/dev/null 2>/dev/null
}

gh_down()
{
	echo "      >>>>> gh download ${1} ${3}"
	cd                  ${RootSD}
	gh release download ${1} -p "${3}"
	chmod               ${2}     ${3}
}

fn_tar()
{
	echo ">>>>> >>>>> targz ${1}"
	cd   ${RootSD}
	tar -czf ../${1}.${2}.tar.gz ${1}
}

fn_run()
{
	case ${1} in
	1)  echo "  > apt-get update"
		sudo apt-get update >/dev/null 2>/dev/null
		echo ">>>>> >>>>> make|run down project"
		mkdir -p ${RootSD}/aia
		cd       ${RootSD}/aia
		fn_install golang
		go build -work -p 4 -ldflags "-s -w" -o run_down ../main.go
		chmod 755 run_down
		cp     ../fs_list_json .
		./run_down
		rm -rf run_down fs_list_json
		echo "     >>>>> log"
		ls | grep *.log
	;;
	2) echo ">>>>> >>>>> jp2 -> png"
		gh_down ${repo_tag} 755 "jp2image"
		cd      ${RootSD}/aia
		jp2image -threads ALL_CPUS -quiet -ImgDir . -OutFor JPG
		rm -rf  *.jp2
	;;
	3) fn_install imagemagick
		echo ">>>>> >>>>> png -> jpg"
		cd        ${RootSD}/aia
		for fs in $(ls | grep .png); do
			convert ${fs} ${fs%.*}.jpg
			rm   -f ${fs}
		done
	;;
	4) echo ">>>>> >>>>> gen vodeo shell"
		cd        ${RootSD}/aia
		gcc       ../gen_shell.c -o ~/cshell
		chmod     755               ~/cshell
		~/cshell  run_ffmpeg
		rm        ~/cshell

		fn_install ffmpeg
		echo "     >>>>> gen start"
		bash       run_ffmpeg ${2}
		echo "     >>>>> gen end"
	;;
	aia) echo ">>>>> >>>>> bug"
		cd       ${RootSD}
		rm  -rf  ${1}
		gh_down  ${repo_tag} 644 "${1}.${2}.tar.gz"
		tar -xzf ${1}.${2}.tar.gz
		rm       ${1}.${2}.tar.gz
	;;
	esac
}

fn_run aia jpg

#fn_run 1
#fn_tar aia jp2

#fn_run 2
#fn_tar aia jpg

#fn_run 3
 fn_run 4 ../../${1}

echo ">>>>> >>>>> end"
